name: 'Draft'
description: 'Draft a release from pull requests'
inputs:
  repo:
    descrition: 'Repository to checkout, defaults to runner'
    required: true
    default: ${{github.repository}}
  prefix:  # id of input
    description: 'prefix to apply to releases, default is "v"'
    required: true
    default: 'v'
  token:
    description: 'Personal Access token for github auth'
    required: true
outputs:
  success: # output will be available to future steps
    description: 'boolean as to weather draft was successfull or not'
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'hard-drive'
  color: 'red'